<?php
/**
 * Author M. Atoar Rahman
 * Date: 24/01/2021
 * Time: 11:40 AM
 */
use App\Model\Profile;
use Illuminate\Database\Seeder;

class ProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [[
            'id' => 1,
            'name_bn' => 'মোঃ মজহারুল হক',
            'name_eng' => 'Md. Mazharul Haque',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 2,
            'constituency_id' => 1,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 1,
            'created_by' => 1
        ],[
            'id' => 2,
            'name_bn' => 'মোঃ নুরুল ইসলাম সুজন',
            'name_eng' => 'Md. Nurul Islam Sujan',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 3,
            'constituency_id' => 2,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 2,
            'created_by' => 1
        ],[
            'id' => 3,
            'name_bn' => 'রমেশ চন্দ্র সেন',
            'name_eng' => 'Ramesh Chandra Sen',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 2,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 4,
            'constituency_id' => 3,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 1,
            'created_by' => 1
        ],[
            'id' => 4,
            'name_bn' => 'আলহাজ্ব মোঃ দবিরুল ইসলাম',
            'name_eng' => 'Alhaj Md. Dabirul Islam',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 5,
            'constituency_id' => 4,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 2,
            'created_by' => 1
        ],[
            'id' => 5,
            'name_bn' => 'মোঃ জাহিদুর রহমান',
            'name_eng' => 'Md. Zahidur Rahman',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 6,
            'constituency_id' => 5,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 3,
            'created_by' => 1
        ],[
            'id' => 6,
            'name_bn' => 'মনোরঞ্জন শীল গোপাল',
            'name_eng' => 'Manoranjan Sheel Gopal',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 2,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 7,
            'constituency_id' => 6,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 3,
            'created_by' => 1
        ],[
            'id' => 7,
            'name_bn' => 'খালিদ মাহমুদ চৌধুরী',
            'name_eng' => 'Khalid Mahmud Chowdhury',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 8,
            'constituency_id' => 7,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 3,
            'created_by' => 1
        ],[
            'id' => 8,
            'name_bn' => 'ইকবালুর রহিম',
            'name_eng' => 'Iqbalur Rahim',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000541222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 9,
            'constituency_id' => 8,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 4,
            'created_by' => 1
        ],[
            'id' => 9,
            'name_bn' => 'আবু হাসান মাহমুদ আলী',
            'name_eng' => 'Abu Hassan Mahmud Ali',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 10,
            'constituency_id' => 9,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 4,
            'created_by' => 1
        ],[
            'id' => 10,
            'name_bn' => 'মোস্তাফিজুর রহমান',
            'name_eng' => 'Mostafizur Rahman',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'spouse_name_bn' => 'Spouse Name Bangla',
            'spouse_name_eng' => 'Spouse Name English',
            'spouse_dob' => '2021-03-15',
            'nid_no' => 1967000111222,
            'spouse_nid_no' => 1967444555666,
            'religion' => 1,
            'pabx_no' => 12345,
            'official_phone' => 12345,
            'residential_phone' => 12345,
            'office_address' => 'House# 01, Road#02',
            'residential_address' => 'House# 01, Road#02',
            'parmanent_address' => 'House# 01, Road#02',
            'user_id' => 11,
            'constituency_id' => 10,
            'parliament_id' => 1,
            'designation_id' => 7,
            'political_parties_id' => 1,
            'birth_district_id' => 1,
            'ministry_id' => 4,
            'created_by' => 1
        ]];

        foreach ($datas as $key => $data) {
            $old = Profile::where('nid_no', $data['nid_no'])->where('user_id', $data['user_id'])->first();
            if (!$old) {
                Profile::create($data);
            }
        }
        // DB::table('profiles')->insert($profiles);
    }
}
