<?php
/**
 * Author M. Atoar Rahman
 * Date: 25/01/2021
 * Time: 11:40 AM
 */
use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'id' => 1,
                'name' => 'Administrator',
                'name_bn' => 'এডমিনিস্ট্রেটর',
                'usertype' => 'speaker',
                'email' => 'admin@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 2,
                'name' => 'Md. Mazharul Haque',
                'name_bn' => 'মোঃ মজহারুল হক',
                'usertype' => 'mp',
                'email' => 'mp1@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 3,
                'name' => 'Md. Nurul Islam Sujan',
                'name_bn' => 'মোঃ নুরুল ইসলাম সুজন',
                'usertype' => 'mp',
                'email' => 'mp2@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 4,
                'name' => 'Ramesh Chandra Sen',
                'name_bn' => 'রমেশ চন্দ্র সেন',
                'usertype' => 'mp',
                'email' => 'mp3@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 5,
                'name' => 'Alhaj Md. Dabirul Islam',
                'name_bn' => 'আলহাজ্ব মোঃ দবিরুল ইসলাম',
                'usertype' => 'mp',
                'email' => 'mp4@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 6,
                'name' => 'Md. Zahidur Rahman',
                'name_bn' => 'মোঃ জাহিদুর রহমান',
                'usertype' => 'mp',
                'email' => 'mp5@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 7,
                'name' => 'Manoranjan Sheel Gopal',
                'name_bn' => 'মনোরঞ্জন শীল গোপাল',
                'usertype' => 'mp',
                'email' => 'mp6@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 8,
                'name' => 'Khalid Mahmud Chowdhury',
                'name_bn' => 'খালিদ মাহমুদ চৌধুরী',
                'usertype' => 'mp',
                'email' => 'mp7@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 9,
                'name' => 'Iqbalur Rahim',
                'name_bn' => 'ইকবালুর রহিম',
                'usertype' => 'mp',
                'email' => 'mp8@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 10,
                'name' => 'Abu Hassan Mahmud Ali',
                'name_bn' => 'আবু হাসান মাহমুদ আলী',
                'usertype' => 'mp',
                'email' => 'mp9@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 11,
                'name' => 'Mostafizur Rahman',
                'name_bn' => 'মোস্তাফিজুর রহমান',
                'usertype' => 'mp',
                'email' => 'mp10@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 12,
                'name' => 'Saidur Rahman',
                'name_bn' => 'সাইদুর রহমান',
                'usertype' => 'ps',
                'email' => 'ps1@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 13,
                'name' => 'Abdul Bari',
                'name_bn' => 'আব্দুল বারী',
                'usertype' => 'ps',
                'email' => 'ps2@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 14,
                'name' => 'Deferral and Rights',
                'name_bn' => 'মুলতবি ও অধিকার',
                'usertype' => 'staff',
                'email' => 'dr@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 3,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 15,
                'name' => 'Law 1',
                'name_bn' => 'আইন ১',
                'usertype' => 'staff',
                'email' => 'law1@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 16,
                'name' => 'Law 2',
                'name_bn' => 'আইন ২',
                'usertype' => 'staff',
                'email' => 'law2@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 5,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ], [
                'id' => 17,
                'name' => 'Question and Answer',
                'name_bn' => 'প্রশ্ন ও উত্তর',
                'usertype' => 'staff',
                'email' => 'qa@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 6,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 18,
                'name' => 'Accommodation Department',
                'name_bn' => 'ডিপার্টমেন্ট',
                'usertype' => 'staff',
                'email' => 'ad1@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 19,
                'name' => 'Whip',
                'name_bn' => 'হুইপ',
                'usertype' => 'staff',
                'email' => 'wh1@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 20,
                'name' => 'Speaker',
                'name_bn' => 'স্পিকার',
                'usertype' => 'speaker',
                'email' => 'speaker@gmail.com',
                'password' => bcrypt('123'),
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 21,
                'name' => 'Administrative Officer',
                'name_bn' => 'প্রশাসনিক কর্মকর্তা (আইন ২)',
                'usertype' => 'staff',
                'email' => 'aol2@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 5,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 22,
                'name' => 'Deputy Secretary',
                'name_bn' => 'উপ সচিব (আইন ২)',
                'usertype' => 'staff',
                'email' => 'dsl2@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 5,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 23,
                'name' => 'Joint Secretary',
                'name_bn' => 'যুগ্ন সচিব (আইন ২)',
                'usertype' => 'staff',
                'email' => 'jsl2@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 5,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 24,
                'name' => 'Senior Secretary',
                'name_bn' => 'সিনিয়র সচিব (আইন ২)',
                'usertype' => 'staff',
                'email' => 'ssl2@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 5,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 25,
                'name' => 'Administrative Officer',
                'name_bn' => 'প্রশাসনিক কর্মকর্তা (মুলতবি)',
                'usertype' => 'staff',
                'email' => 'aodr@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 3,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 26,
                'name' => 'Deputy Secretary',
                'name_bn' => 'উপ সচিব (মুলতবি)',
                'usertype' => 'staff',
                'email' => 'dsdr@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 3,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 27,
                'name' => 'Joint Secretary',
                'name_bn' => 'যুগ্ন সচিব (মুলতবি)',
                'usertype' => 'staff',
                'email' => 'jsdr@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 3,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 28,
                'name' => 'Senior Secretary',
                'name_bn' => 'সিনিয়র সচিব (মুলতবি)',
                'usertype' => 'staff',
                'email' => 'ssdr@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 3,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 29,
                'name' => 'Administrative Officer',
                'name_bn' => 'প্রশাসনিক কর্মকর্তা (আইন ১)',
                'usertype' => 'staff',
                'email' => 'aol1@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 30,
                'name' => 'Deputy Secretary',
                'name_bn' => 'উপ সচিব (আইন ১)',
                'usertype' => 'staff',
                'email' => 'dsl1@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 31,
                'name' => 'Joint Secretary',
                'name_bn' => 'যুগ্ন সচিব (আইন ১)',
                'usertype' => 'staff',
                'email' => 'jsl1@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 32,
                'name' => 'Senior Secretary',
                'name_bn' => 'সিনিয়র সচিব (আইন ১)',
                'usertype' => 'staff',
                'email' => 'ssl1@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 33,
                'name' => 'Administrative Officer',
                'name_bn' => 'প্রশাসনিক কর্মকর্তা (পিটিশন)',
                'usertype' => 'staff',
                'email' => 'aopt@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 34,
                'name' => 'Deputy Secretary',
                'name_bn' => 'উপ সচিব (পিটিশন)',
                'usertype' => 'staff',
                'email' => 'dspt@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 35,
                'name' => 'Joint Secretary',
                'name_bn' => 'যুগ্ন সচিব (পিটিশন)',
                'usertype' => 'staff',
                'email' => 'jspt@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
            [
                'id' => 36,
                'name' => 'Senior Secretary',
                'name_bn' => 'সিনিয়র সচিব (পিটিশন)',
                'usertype' => 'staff',
                'email' => 'sspt@gmail.com',
                'password' => bcrypt('123'),
                'department_id' => 4,
                'remember_token' => 'glfK3hWZnR7TbWGCwV2CfsDh8Q1lVhO9p3Ry7fsWXcVDV1pNJU905JnpYrm9',
            ],
        ];

        foreach ($users as $key => $user) {
            $old = User::where('email', $user['email'])->first();
            if (!$old) {
                User::create($user);
                // DB::table('users')->insert($users);
            }
        }
    }
}
